export const USER_IMAGES_REQUEST = 'USER_IMAGES_REQUEST'
export const USER_IMAGES_SUCCESS = 'USER_IMAGES_SUCCESS'
export const USER_IMAGES_FAIL = 'USER_IMAGES_FAIL'

export const USER_IMAGES_UPLOAD_REQUEST = 'USER_IMAGES_UPLOAD_REQUEST'
export const USER_IMAGES_UPLOAD_SUCCESS = 'USER_IMAGES_UPLOAD_SUCCESS'
export const USER_IMAGES_UPLOAD_FAIL = 'USER_IMAGES_UPLOAD_FAIL'
